on:
  push

jobs:
  Merging_branches:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Sunny"
          git config user.email "Sunnysirohi9@gmail.com"

      - name: Merge dev to master
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git fetch origin main
          git checkout main
          git merge origin/dev --no-ff --commit -m "auto merged dev branch to main"
          git push origin main
