on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install and configure git
        run: |
          git config user.name "Sunny"
          git config user.email "Sunnysirohi9@gmail.com"

      - name: merge dev to master
        run: |
          git fetch --all
          git fetch origin main
          git checkout main
          git merge dev --no-ff --commit -m "auto merged dev branch to main"
          git push origin main
