on:
  push

jobs:
  Merging_branches:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Sunny"
          git config user.email "Sunnysirohi9@gmail.com"
          git clone https://github.com/sunnysirohi/azuredatabase.git
          cp azuredatabase/.github/workflows/* .

      - name: Commit and push to current repository
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git add .
          git commit -m "files added"
          git push origin main
