on:
  push

permissions:
  contents: write
  repository-projects: write
  pull-requests: write

jobs:
  move_repo1content_to_another:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Sunny"
          git config user.email "Sunnysirohi9@gmail.com"
          git clone https://github.com/sunnysirohi/azuredatabase.git
          cp azuredatabase/.github/workflows/* .github/workflows/
          rm -rf azuredatabase

      - name: Commit and push to current repository
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          git checkout main
          git add .
          git commit -m "files added"
          git push origin main
